### ISSUE TITLE
Sync .env with Heroku

### ISSUE THREAD

**Issue by cycomachead** [cs10/Alonzo#75]
There should be a way to locally test by reading Heroku's env variables, and using a local file as a fallback

**Comment by aaaschmitt** [comment]
So for storing .env file I really think we need single source of truth. I'm noticing that it gets weird keeping up with .env file with more than one person working.

Could we set to pull from our github private repo when the bot starts? Like pull the entire file and then set up our env in the executable for  Alonzo script? Would this be too insecure?

**Comment by cycomachead** [comment]
That could would there's a package called
figaro for ruby and I think there's a node counterpart. 

But really we could just pull the env vars from Heroku if we wanted. There a hk get command.   

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by aaaschmitt** [comment]
I think we should just have two .env files in the keys  repo. One is used for local testing and the other is for deployment. Then in each of the executables we set up to pull the correct file.

I think we should try to move away from Heroku env variables because it makes updating the bots environment less intuitive and means that we don't have a SST for our env variables.

**Comment by cycomachead** [comment]
Wait no Heroku means exactly that. Whenever you update Heroku it updates it for everyone. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by aaaschmitt** [comment]
Yeah I guess my problem with heroku is that it's a little annoying changing or reorganizing variables...?

And I don't get what you mean when you say "it updates it for everyone" because right now when people work on the bot they have to pull the env file from github which is not necessarily in sync with the variables in heroku.Heroku env varaibles only apply to the app that is deployed on heroku. We can switch to using only the heroku env vars if you want, but I think a better solution involves not using them at all and keeping a /single/ file in a private git repo that the script then uses pulls from whenever you load the bot.

This ensures that whenever the keys repo changes everyone actually is using the same set of env vars. The local testing script could have an option to use your own env file for testing.

**Comment by aaaschmitt** [comment]
I guess I really would like to streamline the process of adding a new env var. Right what this entails is adding the env var to two places: keys repo and heroku.

In addition, this also means that when testing locally you really should be pulling in a new env before you start working every time which is tedious (and I often don't do).

**Comment by cycomachead** [comment]
That's why we should sync with heroku!
env vars in a file are kinda a pain. :/

you know you can do `hk set` and `hk get` ?
Well, that's with this tool: https://github.com/heroku/hk
`hk env` will dump everything.

The regular `heroku` command line tool uses another word, but it does the
same thing.

This has a lot of good ideas:
https://devcenter.heroku.com/articles/heroku-local#set-up-your-local-environment-variables

The node-figaro package is nice, but unlike the ruby one, it doesn't work
with heroku :(
ᐧ

--
Michael Ball | michaelball.co

**Comment by aaaschmitt** [comment]
Ok I'm fine with that. That's a pretty sweet tool just downloaded it

**Comment by aaaschmitt** [comment]
I prefer a file because version control is nice but we can just do it with heroku

**Comment by cycomachead** [comment]
> I prefer a file because version control is nice but we can just do it with heroku

Yeah, I see that, but given we'd need another repo...it seems harder. :/ 
Heroku does maintain some history:
https://dashboard.heroku.com/apps/alonzo/activity

**Comment by cycomachead** [comment]
I'm gonna set this up:
https://github.com/motdotla/dotenv

**Comment by cycomachead** [comment]
So we can close this now, right? I think thinks are working fine for me...

**Comment by aaaschmitt** [comment]
I made a small change to the file because it wasn't recognizing my remotes. It works now, but have you tried recently?

**Comment by cycomachead** [comment]
Oh yeah, I saw that. Yeah I think it should be fine! :smile:
